hash-format = "sha256"

[[files]]
file = "LICENSE"
hash = "995107821f8e0de23bdf4af01bd99c4bbdac6e419e0913b4d72b47911782c918"

[[files]]
file = "config/bcc-common.toml"
hash = "f4a3a1fca8105a3d91235618058a184a8a240642ccbbf4b1a0ee445d12419416"

[[files]]
file = "config/darkmodeeverywhere-client.toml"
hash = "f53cc3e33e1771c4e0af35c9dd7c9e6c7f1d09ca36ec5b970f933d0dd066dc56"

[[files]]
file = "config/immediatelyfast.json"
hash = "76a1c45855426cfa614135c790b9b3aef1a61f58f3e89f915a6852a1483fbb5e"

[[files]]
file = "config/modernfix-mixins.properties"
hash = "819785f20b5e74c1c12293349f9f439bd0be167a6e6d206ccd3771b51737153f"

[[files]]
file = "config/moreculling.toml"
hash = "ab4182a7cc6ef2f17cce7f37e2956a7b598a61fab6af3f3dc6e4455086880377"

[[files]]
file = "mods/advancement-plaques.pw.toml"
hash = "187911a9d518413b894f9acc9d11c2de91441ce67e7413047d427f6fbb4e6467"
metafile = true

[[files]]
file = "mods/advancements-reloaded.pw.toml"
hash = "127c617d8a6f798a4ead3fa1f3f0084ca5b53538fc7b1920b38a247344164572"
metafile = true

[[files]]
file = "mods/alltheleaks.pw.toml"
hash = "bde2a498b3bfd6e8531bf6bfbe569233ecb4918c42aae6394d900f964a9714e8"
metafile = true

[[files]]
file = "mods/animatica-foxified.pw.toml"
hash = "dbea3bd573f1f343000ea2b140121dd8de6a91ac3b33314e334595753a098363"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "6b0199ba07b1ca61c73cb7b5c5abeaac64572d3007774a1574586c55506f1fc5"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "253dfbe310cbee75744480e368a706d3d0dd45bcfa83685a963c4b13827437f7"
metafile = true

[[files]]
file = "mods/armor-poser.pw.toml"
hash = "95b72a59168b2a9161da059f50b3956ac7247d0e94fb95a2635fb4e185dff0ad"
metafile = true

[[files]]
file = "mods/ash-api.pw.toml"
hash = "aaa823ab125a577145c99dfa1968972e036a52792bd7c0c536e6076a3f18b043"
metafile = true

[[files]]
file = "mods/athena.pw.toml"
hash = "e1599947a8d78f74c129a8420569bb2453b2ce76fdc76a7151093923ea8366c9"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "2955b5a5785789d03fccdfbb44ff5f59185c4beb03b3b1f911b7fb40297c1fae"
metafile = true

[[files]]
file = "mods/baguettelib.pw.toml"
hash = "caf8d9539dfbe24903e1b71f1fb82a37810575b7db57e113a7351dd8d40b60b8"
metafile = true

[[files]]
file = "mods/better-compatibility-checker.pw.toml"
hash = "1d435f1668611f353a386b365cb814fec042758045bf4118320586ebbd881570"
metafile = true

[[files]]
file = "mods/better-modlist-neoforge.pw.toml"
hash = "6b31c751f71bcde18a9065fa6bc097c0d9dc42f788bfe72db563eb8456675238"
metafile = true

[[files]]
file = "mods/builders-jetpack-mod.pw.toml"
hash = "395c6acb1f8893a01ad91d644dbeb4dafb7cda14baa8302654de5c5c2e850655"
metafile = true

[[files]]
file = "mods/c2me.pw.toml"
hash = "0eda65d277f7af698688c84bc473eec386f283a4e78d510364497858a63ec5b6"
metafile = true

[[files]]
file = "mods/camera-mod.pw.toml"
hash = "d8a98b212b5a00a2859a45fd0dea0ce1df3a6ff8fbc5c2bc0bf166b80e217500"
metafile = true

[[files]]
file = "mods/carry-on.pw.toml"
hash = "110a0311063e8d4e6dcd357925fefd96e30e039eee39b4fb8c803b33db55da2e"
metafile = true

[[files]]
file = "mods/chipped.pw.toml"
hash = "3024466ae43de66612dc5ec4cfe5b3a273f71cee29fc6940308798a817d561b6"
metafile = true

[[files]]
file = "mods/chunk-sending-forge-fabric.pw.toml"
hash = "1bade76716eb99c3f2435d2219aceea7781b5534cfe8a7b78f934f24d98347e6"
metafile = true

[[files]]
file = "mods/cit-enchanted-books-hotfix.pw.toml"
hash = "56123c4bf955e6414611ad7553afe6f90ec6204ddbf4fdf2ea6a9876a403d009"
metafile = true

[[files]]
file = "mods/cit-resewn-neopatcher.pw.toml"
hash = "a8b0672f9776f789fa32b0ceb8f2f09d491a30b7955aee7ba267e26ae6907c3d"
metafile = true

[[files]]
file = "mods/cit-resewn.pw.toml"
hash = "e31638605a2bc7cd3a1f9cbf65143c5871cb9eb3bfe766651d965b1145523e1e"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "a15991d53e444b74586301194aa74d23ed60676893fb9d67a1d30bdf2b9f7458"
metafile = true

[[files]]
file = "mods/connectivity.pw.toml"
hash = "44edcc7a691147f940e8083e041bf8258972d22ad316dccfef482026b762eb2b"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "4b03bf7e1c804c0a5b1fdb3fd74ffb8d66947394a81fb192311317af04de2b90"
metafile = true

[[files]]
file = "mods/copycats.pw.toml"
hash = "5634818a1d07c2a10de692aa7bf77326e5eb885da85f1e458af979de8c193fa5"
metafile = true

[[files]]
file = "mods/coroutil.pw.toml"
hash = "0f8a3576c208536b7696060aa1609fb9b0e17d11c2e2c4d251889797717baf83"
metafile = true

[[files]]
file = "mods/corpse-x-curios-api-compat.pw.toml"
hash = "f672a053f6e1dbb49a0361695bc1f01742ce12afee6d4889a4bb45b81f4a4b3c"
metafile = true

[[files]]
file = "mods/corpse.pw.toml"
hash = "1122160ed2c0b6fe91f53403a837a688b8b49641fb7cc94a9e22afe8cf864545"
metafile = true

[[files]]
file = "mods/cosmetic-armor-reworked.pw.toml"
hash = "6db118d947d8db155343014d01e4dbb823d0e187dd401235a3b60654316efe73"
metafile = true

[[files]]
file = "mods/create-design-n-decor.pw.toml"
hash = "9bb04e0450d54cdaaf10120438a5a1139c84fbcf51f9beca3ebb90c9c01eec0a"
metafile = true

[[files]]
file = "mods/create-dragons-plus.pw.toml"
hash = "2dc490a1f0ce5513520112cdc3080899af325d58b7bb7ca218e54b651f665719"
metafile = true

[[files]]
file = "mods/create-enchantment-industry.pw.toml"
hash = "0f33a20021875964144c8297d8b250f640c2fe0c9a3c18203b6697e546a9ec81"
metafile = true

[[files]]
file = "mods/create-escalated.pw.toml"
hash = "cde4872a58b202f6773581f2e0de7d3f62850aca7a077adf162a5e25724b55cc"
metafile = true

[[files]]
file = "mods/create-industry.pw.toml"
hash = "e04d952cedbf936e070e95a302e522e6e8ff3cbe3a9aa0ee5b163d8e174fbdf8"
metafile = true

[[files]]
file = "mods/create-oxidized.pw.toml"
hash = "a33d5f20b82be3bac58e2f238c95751309ffac9a14c6df242c56bcc06369d1fc"
metafile = true

[[files]]
file = "mods/create-power-loader.pw.toml"
hash = "26fd34b3a4c30cf53a15ee29e177b4d26f268ebd650486c90d74c7f67d1d6568"
metafile = true

[[files]]
file = "mods/create-simple-generator.pw.toml"
hash = "cb98e263dd0cea6efbfe7bdb2c682fa4752fd8a19c3fbc90946aabd20b1228f1"
metafile = true

[[files]]
file = "mods/create-stam1o-tweaks.pw.toml"
hash = "17e20682a1ca21de7c0893eba426fcc698b23c8670bc91506e45ef0f51125b87"
metafile = true

[[files]]
file = "mods/create-vibrant-vaults.pw.toml"
hash = "edfc5cfd0224c45873c197c9352eadbe17171f737784581fe32ab963f59f27a3"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "0393b4b25b5527a0fab54d308ee7098ec4155f542417e58b259644589db37f52"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "96305359ebc432052a6fa8021438b65dd029533d4042d9c34311bef826e2294e"
metafile = true

[[files]]
file = "mods/cupboard.pw.toml"
hash = "abff723616a052e15e7281f3c929000aa2bb77e711974cb10115a3c5c4ae7e9b"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "f6e80a16f34084b35334143fd7e8ddd6367aac6c8977de302119ee25229ca07d"
metafile = true

[[files]]
file = "mods/dark-mode-everywhere.pw.toml"
hash = "25327c69a12f46e1a132e2d7c3ba9828747bbba9f2659ad219325948a264442a"
metafile = true

[[files]]
file = "mods/dark-window-bar.pw.toml"
hash = "7f66f222d9dac0962776d92653848fc214b8b5d10405d397eddfd266274ed10a"
metafile = true

[[files]]
file = "mods/deimos-fabric-forge-neoforge.pw.toml"
hash = "737c77b1e8ffcca5a3cdeb1403f4e3989a53fd04ec741395e70ff4ffbb88d701"
metafile = true

[[files]]
file = "mods/distant-horizons.pw.toml"
hash = "0a5833d7150b28af95343031e5260ab6159e00a9c431fcdc3603747b9851666a"
metafile = true

[[files]]
file = "mods/dynamiclights-reforged.pw.toml"
hash = "bed3b7f90ce6408f4e099bd9a90a856a7809f80b77c38ab3062e43d1e199a34b"
metafile = true

[[files]]
file = "mods/eating-animation-forge.pw.toml"
hash = "331965a72cb0240b1f6bbb02e5a2e509b6d046c2b1e99d1ff195430d7012ab20"
metafile = true

[[files]]
file = "mods/emi-enchanting.pw.toml"
hash = "010b33bb4f596fbe470771e45b1c34344c6e68a3c6ccad3375c14a90dda365f9"
metafile = true

[[files]]
file = "mods/emi-loot.pw.toml"
hash = "e9c0f99308388a3fde9cd1422b6b7150606beb2b5c4d1eeebe9acf5277f9a62e"
metafile = true

[[files]]
file = "mods/emi-ores.pw.toml"
hash = "709113ebcd39b2f5efc438e7c5c8f35117d0126d71927a3c8bac47526f3ef6c5"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
hash = "e8b1877c3096768ab430a078797d81a1b71dcead07a10387bc1882276cdddaa4"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "8ce29bf456b2aef550cb8060243e5c227f2679d2c298ee84cfb11bbb81b5cdcf"
metafile = true

[[files]]
file = "mods/euphoria-patches.pw.toml"
hash = "39931c6e95711e66ceb281117795c9b43f157f122fd5093c977b01c43fb8555d"
metafile = true

[[files]]
file = "mods/extra-mod-integrations.pw.toml"
hash = "edebabcf49e0b8423872937b28df210f943425d49d40aa0cfab836a8f7ca78f4"
metafile = true

[[files]]
file = "mods/ferritecore.pw.toml"
hash = "eba3526b8365fccad34dac4e0a3ad18e5861c01eea5c4e8c814b769756c9bdf7"
metafile = true

[[files]]
file = "mods/firefly-bush.pw.toml"
hash = "6a69867745516534cdfcbb7affaa2dabf70e01ba7f80ab7f029025111e0e72e7"
metafile = true

[[files]]
file = "mods/forge-config-api-port-fabric.pw.toml"
hash = "d5a80817b045f43fa2bd19b2895feabf5366b86ec101743eba7ade94bfcd128c"
metafile = true

[[files]]
file = "mods/forgified-fabric-api.pw.toml"
hash = "745fdd8ea00c7afc67099e731afd77da96ec7543c813ba4b51de8568252dfd10"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "bea9d199124b48097cd90674b6d8b99fb269696fd04a17f8fc9b88cbff6c1310"
metafile = true

[[files]]
file = "mods/gml.pw.toml"
hash = "841d57eee40780c5d3acf1deb6e9083a13e43de37890174e9fbec13ec8aa0ee9"
metafile = true

[[files]]
file = "mods/iceberg.pw.toml"
hash = "e7ba94d871017e2cd74fbff31d31887082c60c9324f1d4cccb27d757a84a838f"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "8d0338edc1f2886d41da014673f973508db2da23b830d50c4377afcaf4ced95f"
metafile = true

[[files]]
file = "mods/inventory-sorter.pw.toml"
hash = "984ae733cbcc9012228b3e26b72402e03569c9b54a734155167bc074c9c8f26c"
metafile = true

[[files]]
file = "mods/irisshaders.pw.toml"
hash = "4d063f9bc5d47218a9983ea5d551fce2e0850742cd6ec66b8681cc04c2fb1f42"
metafile = true

[[files]]
file = "mods/jade-addons.pw.toml"
hash = "6d4feee1d352610bbec0ff8858ecf64eec4c07fe8edc3e4992566ba6c01fb65f"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "0c325e87982ff32bcea064e439ffd3a0dc4817f39a729eb70dd666bd381ed70c"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "8b31ca4ceee3b46494fcdf5535a908a9a88ead5e488d0aa5251c6f9e5274d99e"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "a4e6ab10c1e004e6b65a9532c10b1808e1720ced6fbeaa457ea517fe7ffa0bfd"
metafile = true

[[files]]
file = "mods/legendary-tooltips.pw.toml"
hash = "0acb47342c9a3cd8e24981d45de4d8dd8a8bdfae1a2c288fe93913d09df281a2"
metafile = true

[[files]]
file = "mods/light-overlay.pw.toml"
hash = "f26c6ad3309ea5eb93b693812fcdb85c9495bb3b4e4a0e693068d9eceb87c60b"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "3d3dc77fd95dbc9ca9255c22d160644aca3e909d96a63b191befee097448798b"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "ff317ee6e202887121e3dd8b406396aa06ccc88d1b4a1119d52e9fb848c5b3e7"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "7b1c0a43b509dd874f9bbc9f193aae726b1d837468918b01a039ca7d7182deec"
metafile = true

[[files]]
file = "mods/notenoughrecipebook.pw.toml"
hash = "9bc4e7441edda5d7c4bd0eecbec30dc3ebe99675d8e812938444685a366edc92"
metafile = true

[[files]]
file = "mods/octo-lib.pw.toml"
hash = "28137222c7b4096b243b2d65595995465cf2deac0fffce78c9af434680bef83b"
metafile = true

[[files]]
file = "mods/overloaded-armor-bar.pw.toml"
hash = "f5883ecc2673d87510dbd43eec60fd4e2068e7b30104de612ce2fa8f579afc98"
metafile = true

[[files]]
file = "mods/packet-fixer.pw.toml"
hash = "239f5b8f58fd1bcecbae065800eef12f5681952629a161603f65be89e8ae4e1a"
metafile = true

[[files]]
file = "mods/particle-rain.pw.toml"
hash = "9599595171a474920430b33aade7deeb41da48617a13adb37e8519b2f5575c0d"
metafile = true

[[files]]
file = "mods/platform.pw.toml"
hash = "7495782c7215db9f6f49a3d322b7c9aa37b24c0fc87cfda303e965e5cb239c8b"
metafile = true

[[files]]
file = "mods/polymorph.pw.toml"
hash = "e4b6f465c8a9d3afa97a0a6dbd7939bdbb9f61c8293f59f75a2f98cc4856a99f"
metafile = true

[[files]]
file = "mods/prism-lib.pw.toml"
hash = "96674b7ba6bfaece9cc993b6b91d0f66db75bc0bf16ddfcd1c48a026fab88e83"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "cedad7783a39b743dee74a7bb4035dc865e9e85c656468314b642c55f1f0e97d"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "bd30b2013a783f31b6c98ecc798be1efcdddf302c33957b2c3c5fe882b21ad4a"
metafile = true

[[files]]
file = "mods/refined-storage-curios-integration.pw.toml"
hash = "79cf759f8baa2ec5d91f1fc4268aea17c4af8b9c8e0c2d705b61b29c907eb49e"
metafile = true

[[files]]
file = "mods/refined-storage-emi-integration.pw.toml"
hash = "ff5eb080b4ecda47c869c8267d78a8030930245306bc0bf11b4ac258bd7fc59f"
metafile = true

[[files]]
file = "mods/refined-storage-quartz-arsenal.pw.toml"
hash = "d6d2ecfb2ea5ae94c1e6c442bb9347f331011cd26f2193a42ae92737db35ac29"
metafile = true

[[files]]
file = "mods/refined-storage.pw.toml"
hash = "232f18e5eea54607d98b0af5e8e93c213bb534f84a9548fa94ad736762df25da"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "aa83553db30adc47f86010f6443340251323a62ee3f9415a0c4332cb6d502419"
metafile = true

[[files]]
file = "mods/seamless.pw.toml"
hash = "1853a188b4cacf52d8e31d1cd2b943ae1602914a451f05291c096e6a3aaf9429"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "18ab7dbd8b0601163d8788ab1772aa2ce9de29e19431c3b685ef1d1abbc63156"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "800769bd251db47cf9e362bd88f2470a44bc526bb8ed9690f5d26a4f43a1a9a2"
metafile = true

[[files]]
file = "mods/sinytra-connector.pw.toml"
hash = "d564480d7ae1a08790b35398fbe0c6e59d49d2a0d2db005e45a13812a81e4600"
metafile = true

[[files]]
file = "mods/skin-layers-3d.pw.toml"
hash = "6359fb00ada8a864381dd26b6dd21e76ddb904ca2e65c36b19fe7854b5ab5f6c"
metafile = true

[[files]]
file = "mods/smithing-template-viewer.pw.toml"
hash = "b5c4a938bcf1123266afd342d6641d0c0be6198fc934ddd15ae3421f083d0cd9"
metafile = true

[[files]]
file = "mods/smooth-chunk-save.pw.toml"
hash = "be94bc654dd89935d2fd8fa829658558c692692bfc2cf68001f774610dfbd927"
metafile = true

[[files]]
file = "mods/sodium-options-api.pw.toml"
hash = "ce4a46d62bf3f466f4bce7586ecbb77938c581d6cc0a95fd32808c291166153d"
metafile = true

[[files]]
file = "mods/sodium-shadowy-path-blocks.pw.toml"
hash = "8bb95a6cd1ec6a1b667412ad91494c5437d7530cc454cde33e25333760f5ad76"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "3538f5f89357833d9b167908f4e9d9e6511ed940332e1f453f60cccb1f2e5dc6"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "fcb7bdf6030a9dab8ec0366ca8adc92487db3fde2f3934f4caf29511e34101b6"
metafile = true

[[files]]
file = "mods/straw-statues.pw.toml"
hash = "7d4e89b65b0edd50666fdee5a06ef4563b2654c66ac915ab7a2ebbc648170c2c"
metafile = true

[[files]]
file = "mods/transparent.pw.toml"
hash = "d1e68fbdf636814beeb98c4b69a8b65ea7b29983fb1aec45576dd90c607e48b0"
metafile = true

[[files]]
file = "mods/vanillabackport.pw.toml"
hash = "1d5c213f3fb0e01bbbb6fd7eaf31e5a5b0fe3ba98a607be144455954e805a92e"
metafile = true

[[files]]
file = "mods/what-are-they-up-to.pw.toml"
hash = "74f0520f6d59c9ab32513b6747a5dfb33bf8315a0b03b11ce8a417381cb1b059"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
hash = "66e79bd7caef76a03c2266c9ff311b03d0163cd0f1914544ef808f47f0edcb96"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "04b0ab902468b2e1e142da8e5328b00e348f791cee1c47757b037ae946ad0d99"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "d5e9c53f8077d052cddee171fa84e9320f726ceb1a9f623f33e9c877a67b8fd9"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "ae1a7d09f8a3a0e73fa2766f5c9d99e1284c97b03a9045d4d2247a98c33c8ff4"
metafile = true

[[files]]
file = "resourcepacks/clear-glass-pack.pw.toml"
hash = "885ea4102f52958ef9819ced5b7bb850af2d250d4cd48a6fb62d3217d020fd0a"
metafile = true

[[files]]
file = "resourcepacks/enhanced-boss-bars.pw.toml"
hash = "17a234b5a6a0321d1bd3b7cc64a4c7e1c462f3439d777e47457160cd87b1cb87"
metafile = true

[[files]]
file = "resourcepacks/medieval-music-2.pw.toml"
hash = "b59af83a537d88fb6fc1617ae5447490cc90d6647f458175e045f57138de001c"
metafile = true

[[files]]
file = "resourcepacks/small-shield-totem.pw.toml"
hash = "9859f65d141c0d34a124c6edbc7e3952fcf0db1942813f8927df1322503a1af8"
metafile = true

[[files]]
file = "resourcepacks/tropical-fish-buckets.pw.toml"
hash = "14e4c94daa6d73d8d1399626b99c4259aefe4d4c6460fb6bcdd4cc07f4bd96de"
metafile = true

[[files]]
file = "resourcepacks/ultimacraft-enchantments.pw.toml"
hash = "e9ed2301873a0f188d43f3a29ad2985bbb11959dae1ad97d074adbfbe1427a03"
metafile = true

[[files]]
file = "resourcepacks/ultimacraft-interface.pw.toml"
hash = "b9d289953936bfd446b75c7c120f3e6d35e7904b0e1ff482c240eab12321a347"
metafile = true

[[files]]
file = "shaderpacks/complementary-unbound.pw.toml"
hash = "31e87141a28607a05dd37f9e2922a86ccee9ebe966738bb056307caed77cd892"
metafile = true
