name = "Frogmafia's LilyForge"
author = "spokelax"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8122e0ba5e8ef3425c52a57146399e91249ca3e8a78ddacccae36f4f38f909db"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.200"
