name = "Frogmafia's LilyForge"
author = "spokelax"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a1b26e1882b0096d0c9e583c88c524ac9a16613ffc3d0740d46896e780df2092"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.200"
