name = "Frogmafia's LilyForge"
author = "spokelax"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be590db5e517ff7cc6093153243127e59dff031d769a54b1e89ca2dd500f7c6a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.200"
