name = "Frogmafia's LilyForge"
author = "spokelax"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ce842d60b6e0ec260802f3eef03b99abbe638c5c8bdc04a21c667b2a6cd332fb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.200"
