name = "Frogmafia's LilyForge"
author = "spokelax"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cd7a6240db6e7f53f1ad8821426220673917271b1d1791db8bdd48e0a8d25c87"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.200"
